version: 1

inputDir: "content"
outputDir: "web/content/en"
extraInputGlobs:
  - "README.md"
  - "web/assets/favicons"

gitIgnored: true
localLinksStyle:
  hugo:
    indexFileName: "_index.md"

transformations:
  - glob: "../README.md"
    path: /_index.md
    frontMatter:
      template: |
        title: "{{ .Origin.FirstHeader }}"
        lastmod: "{{ .Origin.LastMod }}"
        menu:
          main:
            weight: 1
            pre: <i class='fas fa-book'></i>
        cascade:
        - type: "docs"
          _target:
            path: "/**"

  - glob: "Proposals/README.md"
    path: _index.md
    frontMatter:
      template: |
        title: "{{ .Origin.FirstHeader }}"
        lastmod: "{{ .Origin.LastMod }}"
        menu:
          main:
            weight: 2
            pre: <i class='fas fa-users'></i>

  - glob: "Products/OpenshiftMonitoring/instrumentation.md"
    frontMatter:
      template: |
        title: "{{ .Origin.FirstHeader }}"
        lastmod: "{{ .Origin.LastMod }}"
        weight: 5
  - glob: "Products/OpenshiftMonitoring/collecting_metrics.md"
    frontMatter:
      template: |
        title: "{{ .Origin.FirstHeader }}"
        lastmod: "{{ .Origin.LastMod }}"
        weight: 10
  - glob: "Products/OpenshiftMonitoring/alerting.md"
    frontMatter:
      template: |
        title: "{{ .Origin.FirstHeader }}"
        lastmod: "{{ .Origin.LastMod }}"
        weight: 20
  - glob: "Products/OpenshiftMonitoring/telemetry.md"
    frontMatter:
      template: |
        title: "{{ .Origin.FirstHeader }}"
        lastmod: "{{ .Origin.LastMod }}"
        weight: 30
  - glob: "Products/OpenshiftMonitoring/faq.md"
    frontMatter:
      template: |
        title: "{{ .Origin.FirstHeader }}"
        lastmod: "{{ .Origin.LastMod }}"
        weight: 40

  - glob: "**/README.md"
    path: _index.md
    frontMatter: &defaultFrontMatter
      template: |
        title: "{{ .Origin.FirstHeader }}"
        lastmod: "{{ .Origin.LastMod }}"

  - glob: "**.md"
    frontMatter:
      <<: *defaultFrontMatter

  - glob: "../web/assets/**"
    path: "/../../static/**"

  - glob: "**"
    path: "/../../static/**"
