[build]
  publish = "web/public"
  functions = "functions"

[build.environment]
  # HUGO_VERSION = "..." is set by bingo which allows reproducible local environment.
  NODE_VERSION = "15.5.1"
  NPM_VERSION = "7.3.0"

[context.production]
  command = "make web WEBSITE_BASE_URL=${URL}"

[context.deploy-preview]
  command = "make web WEBSITE_BASE_URL=${DEPLOY_PRIME_URL}"

[context.branch-deploy]
  command = "make web WEBSITE_BASE_URL=${DEPLOY_PRIME_URL}"
