baseURL = "/"
title = "handbook"
theme = ["docsy"]

enableRobotsTXT = true


# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsUseClassic = false
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
# id = "UA-00000000-0"

# Language configuration

[languages.en]
title = "Red Hat Observability Group Handbook"
description = "Red Hat Observability Group Handbook"
languageName = "English"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
# See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
style = "tango"
guessSyntax = "true"

# Comment out if you don't want the "print entire section" link enabled.
[outputs]
section = ["HTML", "print"]

[params]
copyright = "The Red Hat Observability Group Authors"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
# TODO(bwplotka): Changes are suggested to wrong, auto-generated directory, disable for now? Fix it!
github_repo = "https://github.com/rhobs/handbook"
github_branch= "main"
# Enable Algolia DocSearch
algolia_docsearch = true
offlineSearch = false
prism_syntax_highlighting = false

# User interface configuration
[params.ui]
sidebar_menu_compact = false
breadcrumb_disable = false
sidebar_search_disable = false
navbar_logo = true
footer_about_disable = false

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/rhobs/handbook/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/rhobs/handbook/issues/new">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page,
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = true

[[params.links.user]]
name = "GitHub"
url = "https://github.com/rhobs/handbook"
icon = "fab fa-github"
desc = "Ask question, discuss on GitHub!"

[[menu.main]]
name = "Blog #monitoring"
weight = 50
url = "https://www.openshift.com/blog/tag/monitoring"
